### ISSUE TITLE
App not Visible using Lightning AI

### ISSUE THREAD

**Issue by KemalOz21** [Lightning-Universe/Pose-app#100]
To whom it may concern, 

I want to use Lightning AI online website to run Lightning Pose GUI. We were able to create a model from the online GUI and analyze a couple of videos. However, I am getting an error when connecting to the GUI when using the port activation code 7501. How can we resolve this issue?

Thanks,
Kemal
![image](https://github.com/user-attachments/assets/27557a7c-0fc0-4121-9b6d-bb03e02fedda)

**Comment by themattinthehatt** [comment]
closing, see duplicate issue #99
