### ISSUE TITLE
Issue extracting frames to label with WSL 

### ISSUE THREAD

**Issue by AarushShintre** [Lightning-Universe/Pose-app#104]
Hi, we have been using the Pose app for a while now using Linux, and wanted to try using WSL for some new machines. 

When using WSL , the app gets stuck on the extraction process; it finishes extracting all frames but gets stuck in the “motion energy” step. The same video works fine on Linux. We checked the cpu load and it looks like one of the cores is at 100% performance while the others aren’t being used, which differs from what we observed on Linux.

Any suggestions?

**Comment by themattinthehatt** [comment]
WSL does seem to be less stable than natively running in Linux, though I cannot speak to the specific reasons for why that might be. How big are the videos you are trying to process?

**Comment by AarushShintre** [comment]
Oh, I see. The file size might have been an issue then; we are using files around 4GB. The same file goes through fine in Linux , so we will probably stick to using Linux in that case .

**Comment by themattinthehatt** [comment]
I looked back through some of the Discord threads and found someone else that was having the same issue, but it went away when they started using smaller videos - so maybe that is indeed a workaround solution (in addition to just using Linux).

If you're interested here is a function you can use to take a large video and temporally crop out a smaller segment that contains the most movement: https://github.com/Lightning-Universe/Pose-app/blob/9b0380f8af68c9f79fc7a9cf25ade0ad3205e283/lightning_pose_app/backend/video.py#L157

**Comment by AarushShintre** [comment]
Ah, that helps a lot. We will try that . Thank you for the quick response!

**Comment by themattinthehatt** [comment]
Hi @AarushShintre just wanted to close up this issue if possible - were you able to get the extraction working with the smaller file sizes?

**Comment by AarushShintre** [comment]
Hi, sorry about the late response, we were able to get it working with smaller files.
