### ISSUE TITLE
Unable to create new project from source using SLEAP project

### ISSUE THREAD

**Issue by sara-xinyue-liang** [Lightning-Universe/Pose-app#108]
Hi, I was trying to create a project from source using my existing sleap project. In the "Manage Project" tab, after I uploaded my pkg.slp file and defined all keypoints and hit "Create Project", it showed me "Request submitted!" but immediately it showed "... connecting" and then it said "connetion error" (showed in the screenshot)
<img width="652" alt="Screenshot 2024-09-19 at 12 53 54 PM" src="https://github.com/user-attachments/assets/64140a6c-2179-4960-b1dd-d10d7ca0be2d">

Here is what it showed in the terminal:
------------------------------
INFO:APP.BASHWORK:python /teamspace/studios/this_studio/Pose-app/lightning_pose_app/label_studio/create_labeling_config.py --proj_dir /teamspace/studios/this_studio/Pose-app/data/testsleap_1400_02 --filename label_studio_config.xml --keypoints_list Mouth/TB1/TB2/TB3/TB4/TB5/TB6/TB7/TB8/TB9/TB10/TB11/TB12/TB13/Tb14
WARNING:py.warnings:/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/app/utilities/proxies.py:163: You passed a the value '/teamspace/studios/this_studio/Pose-app' as an argument to the `run()` method of root.tensorboard and it looks like this is a path to a file or a folder. Consider wrapping this path in a `lightning.app.storage.Path` object to be able to access these files in your Work.

INFO:APP.BASHWORK:tensorboard --logdir data/testsleap_1400_02/models --host 0.0.0.0 --port 7531 --reload_interval 30
INFO:APP.BASHWORK:streamlit run lightning_pose/apps/labeled_frame_diagnostics.py --server.address 0.0.0.0 --server.port 7533 --server.headless true -- --model_dir=/teamspace/studios/this_studio/Pose-app/data/testsleap_1400_02/models --make_dir --require_tb_logs
INFO:APP.BASHWORK:streamlit run lightning_pose/apps/video_diagnostics.py --server.address 0.0.0.0 --server.port 7534 --server.headless true -- --model_dir=/teamspace/studios/this_studio/Pose-app/data/testsleap_1400_02/models --make_dir --video_subdir video_preds_infer

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

TensorFlow installation not found - running with reduced feature set.

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:7533

INFO:APP.BASHWORK:python /teamspace/studios/this_studio/Pose-app/lightning_pose_app/label_studio/create_new_project.py --label_studio_url http://localhost:7532 --proj_dir /teamspace/studios/this_studio/Pose-app/data/testsleap_1400_02 --api_key whitenoise --project_name testsleap_1400_02 --label_config /teamspace/studios/this_studio/Pose-app/data/testsleap_1400_02/label_studio_config.xml

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

TensorBoard 2.16.2 at http://0.0.0.0:7531/ (Press CTRL+C to quit)

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:7534

An error occurred: index 777 is out of bounds for axis 0 with size 777
INFO: Your Lightning App is being stopped. This won't take long.
INFO: Your Lightning App has been stopped successfully!
INFO: Received SIGTERM signal. Gracefully terminating label_studio.label_studio...
INFO: Received SIGTERM signal. Gracefully terminating tensorboard...
INFO: Received SIGTERM signal. Gracefully terminating streamlit_frame.work...
INFO: Received SIGTERM signal. Gracefully terminating streamlit_video.work...
INFO: Received SIGTERM signal. Gracefully terminating fiftyone...
INFO: Received SIGTERM signal. Gracefully terminating train_ui.work...
Traceback (most recent call last):
  File "/home/zeus/miniconda3/envs/cloudspace/bin/lightning_app", line 8, in <module>
    sys.exit(_cli_entry_point())
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/__init__.py", line 49, in _cli_entry_point
    main()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/app/cli/lightning_cli.py", line 109, in main
    _main()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/app/utilities/exceptions.py", line 37, in invoke
    return super().invoke(ctx)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/app/cli/lightning_cli.py", line 291, in run_app
    _run_app(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/app/cli/lightning_cli.py", line 218, in _run_app
    dispatch(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/app/runners/runtime.py", line 101, in dispatch
    return runtime.dispatch(open_ui=open_ui, name=name, no_cache=no_cache)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/app/runners/multiprocess.py", line 142, in dispatch
    self.app._run()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/app/core/app.py", line 537, in _run
    done = self.run_once()
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/lightning/app/core/app.py", line 478, in run_once
    self.root.run()
  File "app.py", line 357, in run
    self.project_ui.run(action="upload_existing_project")
  File "/teamspace/studios/this_studio/Pose-app/lightning_pose_app/ui/project.py", line 522, in run
    self._upload_existing_project(**kwargs)
  File "/teamspace/studios/this_studio/Pose-app/lightning_pose_app/ui/project.py", line 419, in _upload_existing_project
    df = pd.read_csv(csv_file, header=[0, 1, 2], index_col=0)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/teamspace/studios/this_studio/Pose-app/data/testsleap_1400_02/CollectedData.csv'
[2024-09-19 16:52:55,130] [django.server::log_message::161] [INFO] "GET /api/version HTTP/1.1" 200 904
[2024-09-19 16:52:55,130] [django.server::log_message::161] [INFO] "GET /api/version HTTP/1.1" 200 904
[2024-09-19 16:52:55,192] [django.server::log_message::161] [INFO] "POST /api/projects HTTP/1.1" 201 3195
[2024-09-19 16:52:55,192] [django.server::log_message::161] [INFO] "POST /api/projects HTTP/1.1" 201 3195
[2024-09-19 16:52:55,258] [django.server::log_message::161] [INFO] "POST /api/storages/localfiles HTTP/1.1" 201 362
[2024-09-19 16:52:55,258] [django.server::log_message::161] [INFO] "POST /api/storages/localfiles HTTP/1.1" 201 362
----------------------------------

I can send my pkg.slp file over email if it is helpful for debugging. (it was too big to attach here) The slp file was created using the method " predict > export labels package > labeled frames" mentioned in the thread https://github.com/Lightning-Universe/Pose-app/issues/107

**Comment by themattinthehatt** [comment]
hi @sara-xinyue-liang thanks for reaching out - yes maybe sending us your slp file would be most helpful (m.whiteway [at] columbia.edu)

**Comment by sara-xinyue-liang** [comment]
Hi, I wonder is there any update on what may cause the issue?

Sincerely,
Sara Liang

**Comment by Shmuel-columbia** [comment]
Hi Sara,
Thanks for reaching out! The issue is due to a bug in the code that handles frames without annotations, along with some mapping problems. I’m working on a fix now and will send you the updated code in the next few days so you can convert your SLEAP project to a Lightning Pose project and upload the dataset.

I’ll keep you in the loop as I make progress. Apologies for the inconvenience, and thanks again for flagging this!

**Comment by sara-xinyue-liang** [comment]
Hi @Shmuel-columbia Thank you for helping!

Sara Liang

**Comment by Shmuel-columbia** [comment]
Hi Sara, Sorry for the delay. 
I just wanted to let you know that we are still working on this and will send you a solution as soon as possible.

**Comment by Shmuel-columbia** [comment]
Hi Sara,

I'm sorry it took so long, but we've finally figured out what was causing the issues you were experiencing. The main problems were missing annotations and image dimensions varying between your videos. We're working on a permanent fix for the app to handle these situations better.

In the meantime, I've compiled a Python function to help you convert your pkg.slp file into a Lightning Pose project folder. This code will extract the frames and annotations from your SLEAP .slp file and organize them into a structure compatible with Lightning Pose. You can run this code using Google Colab or on your own computer if you prefer.

Once the script has run:
- Download the output folder to your PC (no need to unzip).
- Start a new project from the source in the app, set the number of views to 1 (for your dataset), and ensure that the keypoints are correct.
- Finally, click "Create Project" and give it some time to load all the images into the app.

Let me know if you have any questions or need any assistance.  

import os
import io
import json
import cv2
import h5py
import numpy as np
import pandas as pd
from PIL import Image
import csv

slp_file_path = "path/to/your/pkg.slp"  # Replace with the path to your .slp file
output_dir = "path/to/output/directory"  # Replace with your desired output directory


def extract_frames_from_pkg_slp(file_path, base_output_dir):
    """
    Extracts frames and keypoint data from a .slp (SLEAP) file, saving them to specified directories.
    Also generates CSV files for frame paths and keypoint coordinates.

    Args:
        file_path (str): Path to the .slp file.
        base_output_dir (str): Directory where extracted data will be saved.

    Creates:
        - labeled-data/: Directory with extracted frames.
        - videos/: Directory reserved for video-related data.
        - selected_frames.csv: CSV file with a list of frame file names per video.
        - CollectedData.csv: CSV file consolidating keypoint data and frame paths.
    """

    # ===========================
    # Step 1: Create Output Directories
    # ===========================
    os.makedirs(base_output_dir, exist_ok=True)
    labeled_data_dir = os.path.join(base_output_dir, "labeled-data")
    os.makedirs(labeled_data_dir, exist_ok=True)
    videos_dir = os.path.join(base_output_dir, "videos")
    os.makedirs(videos_dir, exist_ok=True)
    print(f"Created output directories at {base_output_dir}")

    # ===========================
    # Step 2: Open and Parse the .slp File
    # ===========================
    with h5py.File(file_path, 'r') as hdf_file:
        video_names = {}         # Maps video group names to video filenames
        frame_dimensions = {}    # Stores (width, height) for each video group

        # ---------------------------
        # Extract Video Metadata
        # ---------------------------
        for video_group_name in hdf_file.keys():
            source_video_path = f'{video_group_name}/source_video'
            # Check if the group name starts with 'video' and contains 'source_video'
            if video_group_name.startswith('video') and source_video_path in hdf_file:
                try:
                    # Retrieve the JSON metadata for the source video
                    source_video_json = hdf_file[source_video_path].attrs.get('json', '{}')
                    if source_video_json:
                        source_video_dict = json.loads(source_video_json)
                        video_filename = source_video_dict.get('backend', {}).get('filename')
                        if video_filename:
                            video_names[video_group_name] = video_filename
                            print(f"Found video: {video_filename} in group {video_group_name}")

                            # Extract frame dimensions from the first frame
                            video_data = hdf_file[f'{video_group_name}/video'][:]
                            if len(video_data) > 0:
                                # Convert the first frame's byte data to an image
                                img = Image.open(io.BytesIO(np.array(video_data[0], dtype=np.uint8)))
                                frame_dimensions[video_group_name] = img.size  # (width, height)
                                print(f"Frame dimensions for {video_group_name}: {img.size}")
                            else:
                                print(f"No frames found in {video_group_name}/video.")
                except (json.JSONDecodeError, KeyError) as e:
                    print(f"Error reading video metadata for {video_group_name}: {e}")

        # ---------------------------
        # Determine Maximum Frame Dimensions
        # ---------------------------
        if frame_dimensions:
            # Identify the largest frame size based on area (width * height)
            max_width, max_height = max(frame_dimensions.values(), key=lambda x: x[0] * x[1])
            print(f"Maximum frame dimensions determined: {max_width}x{max_height}")
        else:
            print("No frame dimensions found. Exiting function.")
            return

        data_frames = []    # List to hold DataFrames for keypoint data
        resized_flag = False  # Indicates if any frame was resized

        # ===========================
        # Step 3: Extract and Save Frames
        # ===========================
        for video_group, video_filename in video_names.items():
            # Define the output directory for the current video's frames
            video_base_name = os.path.splitext(os.path.basename(video_filename))[0]
            output_dir = os.path.join(labeled_data_dir, video_base_name)
            os.makedirs(output_dir, exist_ok=True)
            print(f"Processing video group: {video_group}, saving frames to {output_dir}")

            # Check if the 'video' dataset exists within the current group
            if f'{video_group}/video' in hdf_file:
                video_data = hdf_file[f'{video_group}/video'][:]           # Frame image data
                frame_numbers = hdf_file[f'{video_group}/frame_numbers'][:]  # Frame indices
                frame_names = []                                         # List to store saved frame filenames

                # Original frame dimensions for the current video
                original_width, original_height = frame_dimensions[video_group]

                # Iterate over each frame in the video
                for img_bytes, frame_number in zip(video_data, frame_numbers):
                    try:
                        # Convert frame bytes to an image
                        img = Image.open(io.BytesIO(np.array(img_bytes, dtype=np.uint8)))

                        # Resize the image if its dimensions differ from the maximum dimensions
                        if (original_width, original_height) != (max_width, max_height):
                            img = img.resize((max_width, max_height), Image.Resampling.LANCZOS)
                            resized_flag = True  # Set flag since resizing occurred
                            print(f"Resized frame {frame_number} to {max_width}x{max_height}")

                        # Convert the PIL image to a NumPy array for saving with OpenCV
                        img_array = np.array(img)
                        frame_name = f"img{str(frame_number).zfill(8)}.png"  # e.g., img00000001.png
                        frame_path = os.path.join(output_dir, frame_name)
                        cv2.imwrite(frame_path, img_array)  # Save the frame as a PNG file
                        frame_names.append(frame_name)
                        print(f"Saved frame {frame_number} as {frame_name}")
                    except Exception as e:
                        print(f"Error processing frame {frame_number}: {e}")

                # Save the list of frame filenames to a CSV file for reference
                csv_path = os.path.join(output_dir, "selected_frames.csv")
                try:
                    with open(csv_path, 'w', newline='') as file:
                        writer = csv.writer(file)
                        for filename in sorted(frame_names):
                            writer.writerow([filename])
                    print(f"Saved selected frames CSV to {csv_path}")
                except IOError as e:
                    print(f"Error saving selected frames CSV: {e}")
            else:
                print(f"No 'video' dataset found for {video_group}. Skipping frame extraction.")
                continue  # Proceed to the next video group

            # ===========================
            # Step 4: Extract and Save Keypoint Data
            # ===========================
            # Ensure that required datasets exist for keypoint extraction
            if 'frames' in hdf_file and 'points' in hdf_file and 'instances' in hdf_file:
                frames_dataset = hdf_file['frames']
                points_dataset = hdf_file['points']
                instances_dataset = hdf_file['instances']

                # Create a mapping from frame_id to frame_idx for the current video group
                try:
                    video_id = int(video_group.replace('video', ''))
                except ValueError:
                    print(f"Invalid video group name format: {video_group}. Skipping keypoint extraction.")
                    continue

                frame_references = {
                    frame['frame_id']: frame['frame_idx']
                    for frame in frames_dataset
                    if frame['video'] == video_id
                }

                # Create a dictionary to quickly access instances by frame_id
                instances_dict = {inst['frame_id']: inst for inst in instances_dataset}

                data = []  # List to store keypoint data rows

                # Iterate over each frame reference to extract keypoints
                for frame_id, frame_idx in frame_references.items():
                    instance = instances_dict.get(frame_id)
                    if not instance:
                        continue  # Skip if no instance data is found for the frame

                    point_id_start = instance['point_id_start']
                    point_id_end = instance['point_id_end']
                    points = points_dataset[point_id_start:point_id_end]

                    keypoints_flat = []  # Flattened list of keypoint coordinates

                    for kp in points:
                        x, y, vis = kp['x'], kp['y'], kp['visible']

                        # Adjust keypoint coordinates if frames were resized
                        if resized_flag and x is not None and y is not None:
                            x = (x / original_width) * max_width
                            y = (y / original_height) * max_height

                        # Handle invalid or invisible keypoints
                        if x is None or y is None or np.isnan(x) or np.isnan(y) or not vis:
                            keypoints_flat.extend([None, None])
                        else:
                            keypoints_flat.extend([x, y])

                    # Append the frame index and its keypoints to the data list
                    data.append([frame_idx] + keypoints_flat)

                # Parse metadata to retrieve keypoint names and their ordering
                metadata_json = hdf_file['metadata'].attrs.get('json', '{}')
                if metadata_json:
                    try:
                        metadata_dict = json.loads(metadata_json)
                        nodes = metadata_dict.get('nodes', [])
                        skeletons = metadata_dict.get('skeletons', [{}])

                        if not skeletons or 'nodes' not in skeletons[0]:
                            print("Skeleton nodes not found in metadata. Skipping keypoint DataFrame creation.")
                            continue

                        keypoints = [node['name'] for node in nodes]
                        keypoints_ids = [n['id'] for n in skeletons[0].get('nodes', [])]
                        keypoints_ordered = [keypoints[idx] for idx in keypoints_ids]

                        # Define DataFrame columns: 'frame', 'keypoint1_x', 'keypoint1_y', ...
                        columns = ['frame']
                        for kp in keypoints_ordered:
                            columns.extend([f'{kp}_x', f'{kp}_y'])

                        # Create a DataFrame with the extracted keypoint data
                        labels_df = pd.DataFrame(data, columns=columns)

                        # Update the 'frame' column to include the relative path to the frame image
                        labels_df['frame'] = labels_df['frame'].apply(
                            lambda x: f"labeled-data/{video_base_name}/img{str(int(x)).zfill(8)}.png"
                        )

                        # Remove duplicate frames by keeping the first occurrence
                        labels_df = labels_df.groupby('frame', as_index=False).first()

                        # Append the DataFrame to the list of data frames
                        data_frames.append(labels_df)
                        print(f"Extracted keypoint data for video group {video_group}")
                    except (json.JSONDecodeError, KeyError, IndexError) as e:
                        print(f"Error parsing metadata for keypoints: {e}")
                else:
                    print("Metadata JSON not found. Skipping keypoint DataFrame creation.")
            else:
                print("Required datasets ('frames', 'points', 'instances') not found. Skipping keypoint extraction.")

    # ===========================
    # Step 5: Consolidate and Save Keypoint Data
    # ===========================
    if data_frames:
        # Filter out DataFrames that do not contain the 'frame' column or are empty
        non_empty_data_frames = [
            df for df in data_frames
            if 'frame' in df.columns and not df['frame'].isnull().all()
        ]

        if non_empty_data_frames:
            # Combine all non-empty DataFrames into a single DataFrame
            combined_df = pd.concat(non_empty_data_frames, ignore_index=True)
            print(f"Combined DataFrame shape: {combined_df.shape}")

            # Validate that each frame path exists in the filesystem
            combined_df['valid'] = combined_df['frame'].apply(
                lambda path: os.path.exists(os.path.join(base_output_dir, path))
            )
            # Filter out rows with invalid frame paths
            valid_combined_df = combined_df[combined_df['valid']].drop(columns=['valid'])
            print(f"Valid keypoint entries after path verification: {valid_combined_df.shape[0]}")

            if not valid_combined_df.empty:
                # Construct header rows for the final CSV
                scorer_row = ['scorer'] + ['lightning_tracker'] * (len(valid_combined_df.columns) - 1)
                bodyparts_row = ['bodyparts'] + [col.split('_')[0] for col in valid_combined_df.columns[1:]]
                coords_row = ['coords'] + [col.split('_')[1] for col in valid_combined_df.columns[1:]]

                # Create a header DataFrame
                header_df = pd.DataFrame([scorer_row, bodyparts_row, coords_row], columns=valid_combined_df.columns)

                # Combine header and data
                final_df = pd.concat([header_df, valid_combined_df], ignore_index=True)

                # Remove column headers for proper CSV formatting
                final_df.columns = [None] * len(final_df.columns)

                # Define the path for the final consolidated CSV
                final_csv_path = os.path.join(base_output_dir, "CollectedData.csv")

                try:
                    # Save the final DataFrame to CSV without headers and index
                    final_df.to_csv(final_csv_path, index=False, header=False)
                    print(f"Saved keypoint data to {final_csv_path}")
                except IOError as e:
                    print(f"Error saving keypoint data CSV: {e}")
            else:
                print("No valid frame paths found after verification. Final CSV not created.")
        else:
            print("No non-empty DataFrames with 'frame' column to consolidate.")
    else:
        print("No keypoint data was extracted. Final CSV not created.")

# Uncomment to run in this cell
#extract_frames_from_pkg_slp(slp_file_path,output_dir)

**Comment by sara-xinyue-liang** [comment]
@Shmuel-columbia , 

Thank you so much! I will try out the code in these two days and let you know if I have any question.

Sincerely,
Sara Liang
