### ISSUE TITLE
Using Label studio to label frames. 

### ISSUE THREAD

**Issue by ReetKaur15** [Lightning-Universe/Pose-app#49]
Hi, I am trying to use the label studio for labeling the frames using Lightning Pose App. 
I tried to use the username: user@localhost and password: pw 
It didn't wither work nor displaying any error.

could you please provide me solution to this ? 

Thanks and regards :)

**Comment by themattinthehatt** [comment]
Hi @ReetKaur15, sorry for the slow response. I haven't run into this issue before - are you using the labeling app (`labeling_app.py`) or the full app (`app.py`)?

**Comment by themattinthehatt** [comment]
@ReetKaur15 I have finally run into this issue myself now, will be looking into it in the coming days. I'll keep you updated.

**Comment by themattinthehatt** [comment]
Hi @ReetKaur15 

Finally worked this out. Are you using the app in a Lightning Studio, or locally? If a Studio, we released a new studio that has the most recent app installed: https://lightning.ai/themattinthehatt/ai-recipes/lightning-pose-app-v1-0-0~01hgghkdmdpz60ttys95n61852?section=all

We've also been working on docs for the app, we are definitely open to feedback on these!
https://pose-app.readthedocs.io/

**Comment by ReetKaur15** [comment]
@themattinthehatt , Thanks for the update. I am successfully able to manage this.  Thanks :)

**Comment by ReetKaur15** [comment]
@themattinthehatt , I am wondering if you could let me know, if any transformer models available on LightningPose App platform for training pose estimation models?

**Comment by ReetKaur15** [comment]
Thanks @themattinthehatt
