### ISSUE TITLE
extraction volume limit?

### ISSUE THREAD

**Issue by DavidGill159** [Lightning-Universe/Pose-app#73]
I launch the 500mb app and upload my videos (24 x ~200MB .avi files) successfully. But when extracting the frames, frames are extracted for the first 6 videos without issue then the app crashes with a server error.
The extraction appears to continue in my terminal but upon completion I have no way of re-activating the app without losing the extracted data. When uploading 12 videos instead of 24 I don't have this problem, so I assume it is an issue of volume? However, when proceeding to label frames after extracting from 12 videos, **Heidi doesn't detect any projects.**

notes:
- app version: 1.9.1
- local installation as per [method 2](https://lightning-pose.readthedocs.io/en/latest/source/installation.html#:~:text=any%20error%20messages.-,Method%202%3A%20conda%20from%20source,%C2%B6,-First%2C%20ensure%20git)

**Comment by themattinthehatt** [comment]
@DavidGill159 when you look in your filesystem do you see a folder called `Pose-app/data/<your_project>/labeled-data`, and does that folder contain subfolders for the 12 videos you uploaded? Furthermore, do those subfolders have extracted frames, as well as a file called `selected_frames.csv`?

**Comment by DavidGill159** [comment]
Yep, all those files are at the location described.

**Comment by themattinthehatt** [comment]
Hmm ok so it seems the frame extraction worked fine, but something happened while uploading to label studio.

First of all, go ahead and update the app to the latest version by moving into the `Pose-app` directory and running this from the command line:
```
git pull --recurse-submodules
```

Then, try extracting frames from a _single_ video and see if the frames show up in label studio.

**Comment by DavidGill159** [comment]
now the mirror-mouse-example project appears but none of my projects

**Comment by themattinthehatt** [comment]
are they still in the `Pose-app/data` folder?

**Comment by DavidGill159** [comment]
yep

**Comment by themattinthehatt** [comment]
so now when you launch the app you're only seeing the `mirror-mouse-example` project and not yours, correct? One thing to check - the update you just pulled imports the example dataset into the app/label studio automatically. This happens the first time you start the app after the update, but after that it won't interfere with anything. It takes about a minute to import the example dataset, it is possible that during that time the other datasets aren't yet recognized. If you restart the app do you see your projects again?

Thanks for your patience with this :pray:

**Comment by DavidGill159** [comment]
Hi, That is correct. I just tried and still no luck.

**additional note (relevance unknown):** when launching the app with "lightning run app app.py --env STREAMLIT_SERVER_MAX_UPLOAD_SIZE=500" the app does not pop up automatically but instead I have to copy "http://127.0.0.1:7501/view" from my terminal.

**Comment by themattinthehatt** [comment]
Ahhh that's very frustrating, sorry about that. I haven't run into this issue before. Let me see if I can reproduce it on my side and get back to you. I have a meetig coming up soon so it might take a couple of hours, I'll keep you posted.

**Comment by themattinthehatt** [comment]
ok I'm back. I'm not able to reproduce this error on my side. You didn't update your lightning version, correct? (by typing Y into the command line after launching the app). For that you should still be answering N each time.

Another question: if you create a new project now, kill the app, then restart the app, does the new project appear?

**Comment by themattinthehatt** [comment]
> Yes, after killing & re-launching the app, the new project now appears in the label studio! However, I am unable to reproduce this effect when following the same steps again.

Meaning, you are unable to start a new project and get it to appear in label studio; or, you are unable to reproduce the previous projects not showing up in the app?

> Also, after deleting this project, it continues to show up in the label studio.

Yes, this is still on our todo list: https://github.com/Lightning-Universe/Pose-app/issues/50
In the meantime, if you'd like to delete old projects from label studio you can, inside the label studio tab, click on the "Settings" for the project, and delete it manually from there.

> Another note: When creating a project and extracting frames, this message displays for a split second:

Yes, I see this occasionally, but find it difficult to reproduce. I will keep looking into it.

So where do you stand now? Are you able to acccess your older project(s)?

**Comment by DavidGill159** [comment]
> So where do you stand now?
After trialling a bunch of differently formatted projects I have figured out that the label studio is unable to detect projects when the landmark names have spaces or dashes in them, only underscores can be used.

**Comment by themattinthehatt** [comment]
ah ok! very good to know, thanks for figuring that out. I will update the backend code so that spaces and dashes are automatically replaced with underscores.
