### ISSUE TITLE
Saving labelled frames as PNG files with tracked keypoints plotted

### ISSUE THREAD

**Issue by DavidGill159** [Lightning-Universe/Pose-app#77]
Hi, 
I want to directly compare the performance of a lightning pose model to an equivalent DeepLabCut model. the most sensible way to do this is to use my label data from a lightning pose project and load that into DLC. However, in addition to the labelled csvs and extracted frames, DLC also requires the same extracted frames with the keypoints overlayed on the original images. Can I get this out of lightning-pose? i.e. from the label studio?

the standard export feature within label studio doesn't offer png as a format.

EXAMPLE:
![image](https://github.com/Lightning-Universe/Pose-app/assets/116177739/e5bb7098-3753-48fa-b14d-31e0c9a5a1ce)

**Comment by themattinthehatt** [comment]
@DavidGill159 just to clarify, do you want to compare Lightning Pose/DLC using _predicted_ labels from models, or ground-truth labels that you annotated?

**Comment by DavidGill159** [comment]
Hi, I want to use the ground-truth labels that I annotated in LightningPose to train a DLC network. So far I have formatted all the labels and frames as required to train a DLC network. However, DLC requires the labels to be 'checked', the output of which is the frame images with the tracked landmarks.

**Comment by themattinthehatt** [comment]
Ah I see - we don't currently have that feature built into the app. A simple hack would be to just copy the raw frames and name them `_labeled` (or whatever DLC requires) to trick it into thinking you've done the check. If you'd actually like to put hand labels on the frames you'll have to do that yourself. We're wrapping up a bunch of features in the app right now and will start another development cycle in the next couple weeks, and one of the items on the list is to give people more tools to check their hand labels.

**Comment by themattinthehatt** [comment]
This issue has been closed by #89
