### ISSUE TITLE
suddenly cant launch app from terminal

### ISSUE THREAD

**Issue by DavidGill159** [Lightning-Universe/Pose-app#80]
Hi, the last week I have been running lighning-pose training locally from the terminal. Today I need to launch the app to label some more data but I am met with this error. Nothing has changed since the last time I launched the app so I am a bit confused. 
- I am in the pose-app directory 
- I have the latest update for the app 
- I have launched the app in the past with no issue

any help would be much appreciated! 

![image](https://github.com/Lightning-Universe/Pose-app/assets/116177739/06931fcd-8d26-4a01-b0a0-bc06f2968d81)

**Comment by themattinthehatt** [comment]
Did you type "Yes" to the prompt "There is a new version of Lightning, would you like to update?" That is a prompt for the Lightning backend, not our specific app.
We are working on updating things on our end to be compatible with the changes, but we're not there yet. In the meantime you can downgrade lightning and should be able to run the app as before:
```
pip install lightning[app]==2.1.3
```

**Comment by DavidGill159** [comment]
hi, no that prompt did not appear this time. Should I install that within the pose-app directory?

**Comment by themattinthehatt** [comment]
hmm :thinking: 
were you previously using a conda environment? that `ModuleNotFoundError` could pop up if you initially installed the app in a conda env, but then tried to run the app outside of the conda env

**Comment by DavidGill159** [comment]
ah your right, how silly of me. I should be in my environment yes. However, I assume now by installing the app outside the environment I have complicated things a bit? i.e. resulting in this error... 
![image](https://github.com/Lightning-Universe/Pose-app/assets/116177739/5fa57e8c-51a9-404b-9762-e68e6328c10c)

**Comment by themattinthehatt** [comment]
sorry we've been adding some more features - you can run
```
pip install ensemble-kalman-smoother
```
and should take care of that (also in the conda env!)
