### ISSUE TITLE
Error Running Lightning Pose App 

### ISSUE THREAD

**Issue by jonathanlee3** [Lightning-Universe/Pose-app#90]
I am trying to install Lightning Pose app following this [guide](https://pose-app.readthedocs.io/en/latest/) on a desktop with Ubuntu 22.04. So, I made sure to run the 'pip install fiftyone-db-ubuntu2204' line.

The error I am encountering can be seen down below:
![lightningpose_1](https://github.com/Lightning-Universe/Pose-app/assets/123122803/88487dbc-1ff1-4051-85f2-0f1218c6e464)

In this image, after launching the app, I upgraded Lightning Pose to the newest version and running the app failed with the error message being 'ImportError: cannot import name 'optimize_smoothing_params' from 'eks.core.' 

The same issue also occurred when I tried to run it **without** updating the application. 

Another note, a couple weeks ago I was able to successfully set up and run the Lightning Pose app on another desktop with Ubuntu 22.04. However, recently it has not been working. I was wondering what the cause of that could possibly be.

Thank you for your time.

**Comment by themattinthehatt** [comment]
Hi @jonathanlee3, thanks for raising this issue. This error came from us updating the `ensemble-kalman-smoother` package on PyPI to version 2.0.0, but we haven't yet updated the app to be compatible with this change. For now you can just downgrade the EKS package by running (from your Pose app conda environment) `pip install ensemble-kalman-smoother==1.1.0`. Please try this and let me know if that clears up the issue!

**Comment by jonathanlee3** [comment]
> Hi @jonathanlee3, thanks for raising this issue. This error came from us updating the `ensemble-kalman-smoother` package on PyPI to version 2.0.0, but we haven't yet updated the app to be compatible with this change. For now you can just downgrade the EKS package by running (from your Pose app conda environment) `pip install ensemble-kalman-smoother==1.1.0`. Please try this and let me know if that clears up the issue!

Hello @themattinthehatt,

Sorry for getting back to you so late!

After running the line 'pip install ensemble-kalman-smoother==1.1.0' the Lightning Pose app seems to be working perfectly! 

Thank you so much for the help.
